### ISSUE TITLE
Add support for Lightning Labs LND node wallet

### ISSUE THREAD

**Issue by SamuelAl** [sulusolutions/gol402#9]
_Reserved for job candidates_
# Objective
The goal of this issue is to integrate a new wallet implementation into our Golang L402 client that leverages a Lightning Labs LND node as its underlying wallet mechanism. This implementation should adhere to the existing Wallet interface, enabling our system to initiate L402 payments through an LND node.

# Background
Our current architecture involves various wallet implementations that facilitate L402 payments. To enhance our system's flexibility and support for Lightning Network payments, adding an LND node-based wallet is crucial. This would not only expand our payment capabilities but also align our infrastructure with robust, scalable solutions offered by the Lightning Network.

# Requirements

**LND Wallet Implementation:**: Develop a new wallet implementation that conforms to the Wallet interface specified in our wallet package. This implementation must interact with an LND node to process payments, encapsulating all LND-specific logic within.

## Functionality:

- PayInvoice Method: Implement the PayInvoice method to pay a given invoice using the LND node. This includes decoding the invoice, initiating the payment via the LND API, and handling success or failure responses.
Testing:

## Testing
- Unit Tests: Write comprehensive unit tests for the LND wallet implementation, ensuring that each component behaves as expected in isolation.
- End-to-End Tests (Optional but Recommended): If feasible, implement end-to-end tests that simulate the payment process from invoice generation to payment completion using a test LND node. This will help in validating the integration and interaction with the LND node in a scenario close to the production environment.

## Documentation:
Update the project documentation to include details about the LND wallet implementation, setup instructions, and any dependencies or configurations needed.

## Error Handling:
Implement robust error handling within the LND wallet implementation, ensuring that any errors encountered during the payment process are appropriately logged and communicated back through the PaymentResult structure.

# Bounty
Upon successful review and closing of this issue, a bounty of 44,000 sats (approx. 25 EUR) will be rewarded via lightning to the PR contributor.

**Comment by mubarak23** [comment]
@SamuelAl please kindly assign this issue to me

**Comment by mubarak23** [comment]
My though process for this issue implementation

1. Identity the API I need to decode the invoice and pay for it from the LND docs

2. Identity the input for the PayLndInvoice method

3. Implement the decodeInvoice 

4. Implement payAninvoice using the decode voice data 

5. Implement PayLndInvoice that call
    -  the decodeInvoice function 
   - payAninvoice function

6. Write unit test for 
     - decodeInvoice
     - payAninvoice
     - PayLndInvoice

@SamuelAl

**Comment by SamuelAl** [comment]
I think that is a good starting point @mubarak23 , but something missing is the initialization of the LND Wallet abstraction itself.

Here a wallet is just an interface for a system that can pay invoices (the Alby implementation is a good example). To use an LND node to pay an invoice, we first need to initialize an LND client, and expose the pay invoice functionality of the client. For that the user will need to provide connection parameters, such as a macaroon and TLS certificate.

Once the LND client is initialized, paying an invoice might be as simple as using the appropriate LND API call, and decoding the invoice might not even be necessary.

**Comment by mubarak23** [comment]
@SamuelAl i see 
Question
1. Are users providing their node connection parameters, or they will use our node connection parameters to initialize the LND Wallet abstraction (From the Alby implementation, it's doesn't  seem to specify who supply the token) 

from this [doc](https://lightning.engineering/api-docs/api/lnd/invoices/settle-invoice), we can settle an invoice without decoding the invoice, since decoding the invoice, we only need the `num_satoshis` and we will still use the `invoice` and `num_satoshis` to [settle the payment](https://lightning.engineering/api-docs/api/lnd/lightning/send-payment-sync)

**Comment by SamuelAl** [comment]
Users must provide their own connection parameters to connect to their own LND node. The same thing happens with the Alby implementation, the users must provide an auth token to connect to their Alby wallet.

To further clarify, this wallet implementation should only support Lightning Lab's LND node implementation. 

Remember that this library is just an L402 **client**. Users receive the invoice when attempting an L402 request, as part of the L402 handshake (see [this](https://docs.sulu.sh/docs/introduction-to-L402)). They must pay the invoice and provide the preimage as proof of payment back to the L402-enabled server to gain access.

**Comment by mubarak23** [comment]
Awesome, looking at the Alby implementation, i have a better understanding of how to approach this.

**Comment by mubarak23** [comment]
In the LND Docs, the `MACAROON_PATH` and TLS certificate are specified. We collect the paths to these files, then fetch the data from each file and transform it into a hex code.

Since users are bringing their own node parameters, should we expect the string data of the MACAROON FILE or the path to the file? The same question also applies to the TLS certificate.

I'm somewhat stuck on this; if we collect the path, does this mean our server will try to look for the file on our machine, even if it doesn't exist?

**Comment by SamuelAl** [comment]
Just to clarify: what do you mean by "our server"? Do you mean the client's machine, or an L402 API server such as Sulu's servers? Remember that this is the **client** side, the server just generates an invoice that the client must pay, how it pays it does not matter to the server. The way the client is configured is not known to the server. 

If the client chooses to use an LND node to pay invoices (an LND Wallet), it is assumed that the client has access to the macaroon and TLS certificates of their node.

Regarding whether to use files or actual data in the form of hex or base64 strings, ideally both should be supported but if we must choose one I would recommend starting with file paths, since that seems to be the approach followed by most LND-based software.

**Comment by mubarak23** [comment]
i mean Sulu's servers,

**Comment by mubarak23** [comment]
@SamuelAl here is the [PR](https://github.com/sulusolutions/gol402/pull/11) for Review

**Comment by SamuelAl** [comment]
Closed by #12
